### ISSUE TITLE
backup images only

### ISSUE THREAD

**Issue by thijstriemstra** [corsac-s/ipibackup#3]
thanks for this great idea. I would like to backup pictures from my iphone, not the whole disk. I see this uses `idevicebackup2` and looking at it's options it seems to be an all-or-nothing type of backup tool, there's no way to limit it to just pictures. any idea if this is possible and what tool I should use?

**Comment by corsac-s** [comment]
Hi,
idevicebackup2 uses the backup service provided by the device, and yes it's an all or nothing service.
If you want to only get your pictures, you should be able to “mount” the device using `ifuse` and then navigate to the DCIM folder to do a copy using a terminal or a file manager.
