### ISSUE TITLE
Device is not ready yet. Going to try again in 2 seconds...

### ISSUE THREAD

**Issue by paul019** [corsac-s/ipibackup#5]
I followed the described steps exactly using a Raspberry Pi 3B instead of a Raspberry Pi Zero. However, when I connect my iPhone Xs (iOS 12.4.1), the backup does not start.

I connected to my Raspberry Pi via SSH and used `journalctl -f` to see logs. After connecting the iPhone, I could read `Device is not ready yet. Going to try again in 2 seconds...` there over and over. What is the problem here?

**Comment by paul019** [comment]
I tried again with my iPad, that already runs on iPadOS 13.4 und it worked! However, I am not currently planning on updating my iPhone to iOS 13, so is there a solution to make it work with iOS 12, too?

**Comment by corsac-s** [comment]
If you have the `device is not ready yet` message, then ipibackup is working fine and running idevicebackup2. Everything else is done by libimobiledevice so you should report this upstream (https://github.com/libimobiledevice/libimobiledevice/issues). Unfortunately, if it works on iOS 13 and not on iOS 12, I'm unsure if it'll really be fixed.
