### ISSUE TITLE
Status LED

### ISSUE THREAD

**Issue by paul019** [corsac-s/ipibackup#6]
I would like to have four status LEDs instead of one, so that they can show the percent progress of the backup (1 LED on = 25 %, 2 LEDs on = 50 %,...). Is that somehow possible with `idevicebackup2`? If so, can you give me a hint, how to realize that?

**Comment by corsac-s** [comment]
You'd have to parse the output from idevicebackup2 and I really don't think it's intended that way. See also https://github.com/libimobiledevice/libimobiledevice/issues/667

I don't think there's much which can be done here.
